theme: jekyll-theme-cayman
title: Are Housing Prices in University Towns Less Affected by Recessions?
description: Based on the assignments from Introduction to Data Science in Python by University of Michigan on Coursera
